version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
  meetup-next-app:
    image: henriquemazzoleni/meetup-next-app
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app

volumes:
  data: